name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests unitaires
        run: npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/realtime-dashboard:latest .

      - name: Push image Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/realtime-dashboard:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement sur le serveur
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/realtime-dashboard:latest
            docker stop dashboard || true
            docker rm dashboard || true
            docker run -d --name dashboard -p 80:5173 ${{ secrets.DOCKER_USERNAME }}/realtime-dashboard:latest
